<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<h3>Cache host settings</h3>
	<div class="form-group">
		<label class="group-name" for="image_cache_url"><?php echo _t('ext.imagecache.cache_url'); ?></label>
		<div class="group-controls">
			<input type="url" name="image_cache_url" id="image_cache_url" value="<?php echo $this->settings->getImageCacheUrl(); ?>">
		</div>
	</div>
	<div class="form-group">
		<label class="group-name" for="internal_image_cache_url"><?php echo _t('ext.imagecache.internal_cache_url'); ?></label>
		<div class="group-controls">
			<input type="url" name="internal_image_cache_url" id="internal_image_cache_url" value="<?php echo $this->settings->getInternalImageCacheUrl(); ?>">
		</div>
	</div>
    <div class="form-group">
        <label class="group-name" for="image_cache_access_token"><?php echo _t('ext.imagecache.access_token'); ?></label>
        <div class="group-controls">
            <input type="text" name="image_cache_access_token" id="image_cache_access_token" value="<?php echo $this->settings->getImageCacheAccessToken(); ?>">
        </div>
    </div>
    <h3>Caching settings</h3>
    <div class="form-group">
        <label class="group-name" for="image_recache_url"><?php echo _t('ext.imagecache.image_recache_url'); ?></label>
        <div class="group-controls">
            <textarea name="image_recache_url" id="image_recache_url"><?php echo implode("\n", $this->settings->getImageRecacheUrl()); ?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="image_cache_disabled_url"><?php echo _t('ext.imagecache.cache_disabled_url'); ?></label>
        <div class="group-controls">
            <textarea name="image_cache_disabled_url" id="image_cache_disabled_url"><?php echo implode("\n", $this->settings->getImageDisabledUrl()); ?></textarea>
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="upload_retry_count"><?php echo _t('ext.imagecache.upload_retry_count'); ?></label>
        <div class="group-controls">
            <input type="number" step="1" min="0" max="100" name="upload_retry_count" id="upload_retry_count" value="<?php echo $this->settings->getUploadRetryCount(); ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="upload_retry_delay"><?php echo _t('ext.imagecache.upload_retry_delay'); ?></label>
        <div class="group-controls">
            <input type="number" step="1" min="0" max="300" name="upload_retry_count" id="upload_retry_delay" value="<?php echo $this->settings->getUploadRetryDelay(); ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="max_cache_elements"><?php echo _t('ext.imagecache.max_cache_elements'); ?></label>
        <div class="group-controls">
            <input type="number" step="1" min="1" max="999999" name="max_cache_elements" id="max_cache_elements" value="<?php echo $this->settings->getMaxCacheElements(); ?>">
        </div>
    </div>
    <h3>Display settings</h3>
    <div class="form-group">
        <label class="group-name" for="video_default_volume"><?php echo _t('ext.imagecache.video_default_volume'); ?></label>
        <div class="group-controls">
            <input type="number" step="0.01" min="0" max="1" name="video_default_volume" id="video_default_volume" value="<?php echo $this->settings->getVideoDefaultVolume(); ?>">
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="image_cache_remove_wrong_tag"><?php echo _t('ext.imagecache.remove_wrong_tag'); ?></label>
        <div class="group-controls">
            <input type="text" name="image_cache_remove_wrong_tag" id="image_cache_remove_wrong_tag" value="<?php echo $this->settings->isRemoveWrongTag(); ?>">
        </div>
    </div>
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
			<button type="reset" class="btn"><?php echo _t('gen.action.cancel'); ?></button>
		</div>
	</div>
</form>
